name: Build, Package, Release (dev)
'on':
  release:
    types:
      - created
  push:
    branches:
      - dev
env:
  VERSION: null
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Get last commit hash
        id: lasthash
        run: |
          LAST_HASH=$(git rev-parse --short HEAD)
          echo "LAST_HASH=$LAST_HASH" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.MO_REGISTRY_AUTH_URL__DEV }}
          username: ${{ vars.MO_REGISTRY_USER__DEV }}
          password: ${{ secrets.MO_REGISTRY_PAT__DEV }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ${{ vars.MO_DOCKERCONTEXT__DEV }}
          file: ${{ vars.MO_DOCKERFILE__DEV }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ vars.MO_IMAGE_NAME__DEV }}:${{ env.VERSION }}
            ${{ vars.MO_IMAGE_NAME__DEV }}:latest
            ${{ vars.MO_IMAGE_NAME__DEV }}:${{ env.LAST_HASH }}
          build-args: VERSION=${{ env.VERSION }}
      - id: releaseWithMogenius-12FF1AABB4D88A98895A
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ vars.MO_IMAGE_NAME__DEV }}:${{ env.VERSION }}
          kind: Deployment
          namespace: offo-dev
          resourceName: off-frontend
          containerName: off-frontend
          keyKind: ${{ vars.MO_API_KIND__DEV }}
          token: ${{ secrets.MO_API_TOKEN__12FF1AABB4D88A98895A__DEV }}
